version: "3.9"

services:
	db:
		image: postgres:16-alpine
		container_name: ilovecomix-db
		restart: unless-stopped
		environment:
			POSTGRES_USER: ilovecomix
			POSTGRES_PASSWORD: ilovecomix
			POSTGRES_DB: ilovecomix
		ports:
			- "5432:5432"
		volumes:
			- ilovecomix_pgdata:/var/lib/postgresql/data

volumes:
	ilovecomix_pgdata:
